name: FreeCAD Addon Tests

on:
  push:
    branches: [ "testing-main" ]
  pull_request:
    branches: [ "testing-main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install FreeCAD
      run: |
        sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        sudo apt-get update
        sudo apt-get install -y freecad freecad-python3

    - name: Set PYTHONPATH for FreeCAD
      run: echo "PYTHONPATH=/usr/lib/freecad/lib:\$PYTHONPATH" >> $GITHUB_ENV

    - name: Log PYTHONPATH
      run: echo "PYTHONPATH is $PYTHONPATH"

    - name: Install Python dependencies
      run: |
        python -m venv testing-env
        source testing-env/bin/activate
        pip install -r requirements.txt

    - name: Check Python and FreeCAD installation
      run: |
        source testing-env/bin/activate
        python --version
        python -c "import FreeCAD"

    - name: Run tests
      run: |
        source testing-env/bin/activate
        pytest
